### ISSUE TITLE
Add CI integration

### ISSUE THREAD

**Issue by fosslinux** [gophernicus/gophernicus#10]
Ideally, we want to have CI avaliable so we can see that PR's build and run correctly without having to build them ourselves to test.

Which CI should we use?

Travis CI is good but has outdated OS (Ubuntu 14.04 by default, 16.04 experimental)

**Comment by hb9kns** [comment]
As I have absolutely no experience with CI, I'll keep out of this one for the time being!

**Comment by jamestomasino** [comment]
Travis probably has the lowest bar to entry. I'd suggest going with that to start. If something better comes along later then it's trivial to update.

**Comment by fosslinux** [comment]
I've been working on Travis, which seems to be mostly working. It has picked up what I think is a bug on Fedora 29. However, to integrate it with gophernicus, I need to have "Admin" permissions, which you can't  do on a user's repo, so that's why I want to move to an org.

**Comment by fosslinux** [comment]
Done a while ago, moving to Drone CI but that's off-topic for here.
