### ISSUE TITLE
Permission error with main gopher folder on Ubuntu 16.04

### ISSUE THREAD

**Issue by spriteclad** [gophernicus/gophernicus#15]
Not sure if this is because of my OS version or not, but when I tried to run Gophernicus when it's serving a folder with full write/read/execute permissions (doesn't matter which account owns it or where it's located), it gives me an 'Access denied!' error whenever I try to access it from a Gopher client. Any ideas as to why this could be?

I'm running on Ubuntu 16.04, if that helps. I also tried to make the .deb version of Gophernicus, but it just gave me an error while trying to do it with sudo.

**Comment by fosslinux** [comment]
Can you open a separate issue for the .deb version of Gophernicus? thanks.

Is this gopher server open to the web? If so, can I please have the uri so I can reproduce?

Can I please see the output of `ls -lR /your/gopher/root`?

**Comment by spriteclad** [comment]
I haven't reinstalled Gophernicus on my VPS yet, but I'll do that as soon as possible. Also, the deb version isn't making because I don't have the prerequisites. Where would I get them?

**Comment by spriteclad** [comment]
![image](https://user-images.githubusercontent.com/11656143/56460356-60918e80-6356-11e9-8415-de9221d247f5.png)
Here's the output of the `/var/gopher` folder you wanted from me.

**Comment by fosslinux** [comment]
`cat /var/gopher/gophermap` please, and change the permissions to 644 unless it needs to be executed.

**Comment by spriteclad** [comment]
![image](https://user-images.githubusercontent.com/11656143/56463417-bf6ffb80-6388-11e9-968a-ec0627def8ae.png)

**Comment by spriteclad** [comment]
Also, changed perms of `/var/gopher` to 644, and now my server is saying 'Error: File or directory not found!'

**Comment by fosslinux** [comment]
sorry, my bad. i meant `/var/gopher` to 755 and `/var/gopher/gophermap` to 644.

**Comment by spriteclad** [comment]
![image](https://user-images.githubusercontent.com/11656143/56471802-a197aa80-640b-11e9-8107-838392a77ba2.png) 

Did that, but site is still telling me 'File or directory not found!'

**Comment by fosslinux** [comment]
hmmm. Can you make gophermap 755 and phlog directory also 755. Can you also try `chown -R gopher:gopher /var/gopher`?

**Comment by spriteclad** [comment]
No, I am not using burrow. Also, none of those things worked.

**Comment by fosslinux** [comment]
I just tried to access your gopherhole, and I got
```
/var/gopher//gophermap: 2: /var/gopher//gophermap: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-: not found
/var/gopher//gophermap: 4: /var/gopher//gophermap: Nothing: not found
/var/gopher//gophermap: 6: /var/gopher//gophermap: Syntax error: "(" unexpected
       _________________________________________________________________________
___
                                Gophered by Gophernicus/129 on Ubuntu/16.04 x86_
64
````

Ummm, what?

**Comment by jamestomasino** [comment]
You instructed @spriteclad to make the gophermap executable (755). Now it thinks it's a shell script. In this case it's a normal gophermap and should be 644. The directories should be 755.

**Comment by fosslinux** [comment]
Ah, my bad, I totally forgot about that. That was a tired-brain comment haha.

**Comment by spriteclad** [comment]
Okay, but I still want to be able to edit the files with FTP on my regular un-elevated user. Is there no way to get the files to be editable with read and write perms?

**Comment by jamestomasino** [comment]
I'd suggest adding your user and those files to a common group, maybe "gopher", and changing the permissions to 775 and 664 for directories and files respectively to accomplish that goal.

**Comment by spriteclad** [comment]
Can you tell me how to accomplish the group thing? I changed the permissions though, and that seemed to do the trick.

**Comment by jamestomasino** [comment]
You'll want to create a group (`sudo groupadd ...`) and then add your user to that group (`sudo usermod -a -G groupname username`) and then change the files in that folder to use that group (`sudo chgrp groupname /path/to/files/*`).

**Comment by spriteclad** [comment]
Ah, okay. I'll try that. Thank you very much!

**Comment by fosslinux** [comment]
Hey, looks like it's working! Is your problem now solved?

**Comment by fosslinux** [comment]
"will just immediately stop recognizing the main directory
you use for gopher when you set the folder's perms to full read/write/execute (aka
777)"

from your phlog, I can answer that. This is by design. gophernicus is meant to be secure, and as you can see https://github.com/gophernicus/gophernicus/blob/master/gophernicus.c#L727 here, world-writable is not allowed. I can add a flag to disable that, however, if that is wanted.

**Comment by jamestomasino** [comment]
I'd suggest not adding a flag to weaken gophernicus security. World-writable isn't something we should encourage and there's other ways to get the same benefit with group permissions.

**Comment by fosslinux** [comment]
That's true, you have a good point there.

**Comment by spriteclad** [comment]
I think it's solved, but I'm wondering if the permissions will be the same if I add new files or folders to the gopher folder. Hopefully I won't have to redo the permissions every time.

**Comment by fosslinux** [comment]
As long as /var/gopher is owned by the gopher group, it'll inherit the permissions.
