### ISSUE TITLE
Port/Support for Oracle Solaris 11.4 and 11.next

### ISSUE THREAD

**Issue by AntonMcClure** [gophernicus/gophernicus#18]
Applies to: Oracle Solaris 11.4 (SunOS 5.11) & 11.next

When running `make` and `sudo make install` on Oracle Solaris 11.4 (SunOS 5.11), it gives the error `sh: update-inetd: not found [No such file or directory]` without trying to use Service Management Facility.

The /etc/inetd.conf is no longer directly used to configure inetd.  Service Management Facility should be used instead.

Information on SMF is available on Oracle Solaris at `man smf` or online at https://docs.oracle.com/cd/E88353_01/html/E37853/smf-7.html#scrolltoc, and service templates provided by Oracle Corp. are available on Oracle Solaris at `man smf_template` or online at https://docs.oracle.com/cd/E88353_01/html/E37853/smf-template-7.html#scrolltoc.

**Comment by fosslinux** [comment]
It's highly unlikely that we will be able to support SMF, unfortunately, but PR's are much welcome. I don't know about @hb9kns but I know 0 about Solaris.

However, I can tell you that this is a sort-of-bug. `sh: update-inetd: not found [No such file or directory]`
I'll make a PR to fix it, and you can try that. You won't be able to run gophernicus through SMF, but you can run it directly and leave it in a tmux/screen, for example, or run it in the background.

**Comment by AntonMcClure** [comment]
> I don't know about @hb9kns but I know 0 about Solaris.
Feel free to ask me about any OS-spefic issues you encounter with the fix

**Comment by AntonMcClure** [comment]
I'm just going to make a PR to fix it, and write documentation for how to run it with SMF (If possible).

**Comment by fosslinux** [comment]
Since Solaris isn't really even supported, I'm changing this to a porting issue.

**Comment by AntonMcClure** [comment]
just a quick question: what is supported?

**Comment by AntonMcClure** [comment]
Based on new information, this issue will be closed.

**Comment by fosslinux** [comment]
New information? What new information?

**Comment by AntonMcClure** [comment]
It was just "isn't really supported", If it can still be ported, then I suppose the issue could be re-opened

**Comment by fosslinux** [comment]
@AntonMcClure  assigned you ask per request

**Comment by AntonMcClure** [comment]
Name changed to reflect development and testing that will be done on 11.4 and the 11.x beta versions.

**Comment by fosslinux** [comment]
@AntonMcClure progress at all?

**Comment by fosslinux** [comment]
@AntonMcClure progress at all?

**Comment by augfab** [comment]
Hi,
I did some changes (https://github.com/augfab/gophernicus/commit/533975afe69e95ea298954679fd1ca6d00b81016) in order to “port” `gophernicus` to OmniOS, an OpenSolaris-derived system that uses SMF.

I don't have an Oracle Solaris box where I could test these changes, but I guess it could work there without much additional effort.

```$ uname -a
SunOS omnios.augfab.dev 5.11 omnios-r151034-b3d6e2addc i86pc i386 i86pc
```

gopher://omnios.augfab.dev serves the default gophermap, `/caps.txt`, and `/server-status.txt`:
```
$ nc omnios.augfab.dev 70 <<</
iWelcome to Gophernicus!	TITLE	null.host	1
i _______               __                      __		null.host	1
i|     __|.-----.-----.|  |--.-----.----.-----.|__|.----.--.--.-----		null.host	1
i|    |  ||  _  |  _  ||     |  -__|   _|     ||  ||  __|  |  |__ --		null.host	1
i|_______||_____|   __||__|__|_____|__| |__|__||__||____|_____|_____		null.host	1
i               |__|		null.host	1
iIf you can see this, it means that the installation of Gophernicus		null.host	1
ion this system was successful. You may now add content to this		null.host	1
idirectory and replace this page.		null.host	1
i		null.host	1
iGeneric information:		null.host	1
i    your ip address: 90.116.249.62		null.host	1
i    server time....: Thu Sep  3 20:42:22 UTC 2020		null.host	1
i    server uptime..: 1 day(s)		null.host	1
i    server version.: Gophernicus/3.1 "Dungeon Edition"		null.host	1
i    server platform: SunOS/5.11 i86pc		null.host	1
i    description....: 		null.host	1
i		null.host	1
iServer configuration:		null.host	1
i    config file....: /etc/inetd.conf		null.host	1
i    server hostname: omnios.augfab.dev		null.host	1
i    root directory.: /var/gopher		null.host	1
i    running as user: nobody		null.host	1
i    output charset.: UTF-8		null.host	1
i    output width...: 67 characters		null.host	1
i		null.host	1
i___________________________________________________________________		null.host	1
i                   Gophered by Gophernicus/3.1 on SunOS/5.11 i86pc		null.host	1
.
```
```
$ nc omnios.augfab.dev 70 <<</caps.txt
CAPS

##
## This is an automatically generated caps file.
##

CapsVersion=1
ExpireCapsAfter=1800

PathDelimeter=/
PathIdentity=.
PathParent=..
PathParentDouble=FALSE
PathKeepPreDelimeter=FALSE
ServerSupportsStdinScripts=TRUE
ServerDefaultEncoding=UTF-8
ServerTLSPort=0

ServerSoftware=Gophernicus
ServerSoftwareVersion=3.1 "Dungeon Edition"
ServerArchitecture=SunOS/5.11 i86pc
```
```
$ nc omnios.augfab.dev 70 <<</server-status.txt
Total Accesses: 9
Total kBytes: 5
Uptime: 274
ReqPerSec: 0.033
BytesPerSec: 18
BytesPerReq: 512
BusyServers: 1
IdleServers: 0
CPULoad: 0.00
Total Sessions: 1
```

**Comment by fosslinux** [comment]
Would you mind if I included this with the build system rewrite? That's currently what I' working on for gophernicus.

**Comment by augfab** [comment]
Sure! Glad you're interested 😃

Are your changes for the build system rewrite visible somewhere?

It's still a bit of a work in progress, I need to test on a freshly installed machine.

`cc` doesn't exist in OmniOs, so I need to select an other compiler, by running
```bash
$ make CC=gcc
```
And I needed to add `gopher` to the list of known protocols:
```bash
if ! grep -q gopher /etc/inet/services; then
    echo 'gopher 70/tcp' >>/etc/inet/services
fi
```

**Comment by fosslinux** [comment]
> Are your changes for the build system rewrite visible somewhere?

Not quite yet, it isn't complete yet, however I do plan to push it to a branch as soon as it has feature parity.

**Comment by AntonMcClure** [comment]
I forgot about this.  I haven't used Solaris for a while now, and I don't really see any use for it, as there are many (better) and fully free operating systems out there which support this program already.  Closing issue.

**Comment by AntonMcClure** [comment]
Can this get re-labeled with "wontfix"?

**Comment by tallship** [comment]
> Can this get re-labeled with "wontfix"?

Thanks for your input @AntonMcClure , but I'm thinking, and recommending that, we leave this open since sometime else might come along so we can bring this to conclusion.

I'm still running on Solaris 10, so these issues don't doesn't affect me personally at this time, and if I eventually move to Solaris 11+ i might try to tackle this.

But ultimately, it's up to @fosslinux to decide.

⛵

.
