### ISSUE TITLE
Move to org.

### ISSUE THREAD

**Issue by fosslinux** [gophernicus/gophernicus#26]
There are now many reasons to move to our new organization, at github.com/gophernicus. These are primarily so that myself and yargo (@hb9kns) can do more administrative stuff, most notably my new plans for Travis CI.

However, this will require @kimholviala to move it to the org. Kim, if you are willing to, can you please move this? I've added you as an owner to the org. Thanks.

**Comment by kimholviala** [comment]
Howdy,

Once again I'm not a Github-guru so hopefully the transfer to the new organization went well...


- Kim

**Comment by fosslinux** [comment]
Thank you very much :+1:
