### ISSUE TITLE
Committed Conflict Markers!

### ISSUE THREAD

**Issue by vext01** [gophernicus/gophernicus#35]
The following commit adds conflict markers to README.md!
https://github.com/gophernicus/gophernicus/commit/c2da2d70b636100d98df2aef328bb4a7a171bf85

I'm guessing you didn't mean to do that!

**Comment by vext01** [comment]
CC @fosslinux (author of commit in question)

**Comment by fosslinux** [comment]
oh flip, let me fix that :D

**Comment by fosslinux** [comment]
Ok, fixed and re-added new stuff, thanks!
