### ISSUE TITLE
make deb issues -branch 3.0.1

### ISSUE THREAD

**Issue by tallship** [gophernicus/gophernicus#45]
As per the instructions specified by INSTALL.md, when attempting to create a package using `make deb`, it fails with the following:

```
$ make deb
dpkg-buildpackage -rfakeroot -uc -us
dpkg-buildpackage: error: fakeroot not found, either install the fakeroot
package, specify a command with the -r option, or run this as root
make: *** [Makefile:74: deb] Error 255
```

If the user shouldn't be sudo'ing then perhaps _fakeroot_ package might need to be listed as a dep for creating .deb packages?

After an `su -`, The following error occurs:

```
# make deb
dpkg-buildpackage -rfakeroot -uc -us
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: error: gain-root-command 'fakeroot' not found
make: *** [Makefile:74: deb] Error 2
```
When sudo is invoked as the non-privileged user:

```
$ sudo make deb
[sudo] password for joeschmoe:
dpkg-buildpackage -rfakeroot -uc -us
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: error: gain-root-command 'fakeroot' not found
make: *** [Makefile:74: deb] Error 2
```

Tests performed on Gophernicus branch 3.0.1

**Comment by fosslinux** [comment]
yep, you need to install `fakeroot`, I think.

**Comment by fosslinux** [comment]
I now see where this was missed. `build-essential` pulls in `dpkg-dev`, which recommends fakeroot. By default, debian/ubuntu systems pull in fakeroot, but maybe you disabled that?
