### ISSUE TITLE
Binaries deep within a nest of directories download with trash added to filename

### ISSUE THREAD

**Issue by DavidGriffith** [gophernicus/gophernicus#48]
I noticed that some files downloaded from a Gopher site that exist more than X directories down will get extra stuff appended to the filename.  This stuff appears to be metadata having to do with the file.  For instance, go to gopher.661.org and look at the Yaesu VX-7 files.  Try to download something.  All is well.  Now go to the Interactive Fiction Archive mirror (also at 661.org) and navigate to "Infocom Zcode" at the bottom.  Then to "frotz" and try to download something from there.  You'll be offered a file named something like `dfrotz.zip----------------------------2015-Oct-27-`

**Comment by fosslinux** [comment]
What client are you using? Unable to reproduce with lynx,

**Comment by DavidGriffith** [comment]
I was using the UM Gopher client version 3.0.16.  This is what Debian installs when you do `apt-get install gopher`.

**Comment by tallship** [comment]
Hi David,

I tried following the events you described, downloaded several items such as dfrotz.zip, frotz243.zip, FrotzCESource_130.zip, and FrotzGS.shk with the following clients on the following platforms:

### Windows 10/64:

* Gopher Browser for Windows v1.2
 
* Simple Gopher Client v1.4
 
* Elpher Gopher Client version 2.3.5

### UNIX (Debian/64 Bullseye)

* Internet Gopher Information Client 3.0 patch12 (FurryTerror)

* Elpher Gopher Client version 2.3.5

***RESULTS***:

No abnormal behavior at all on Windows platforms. On UNIX (Debian GNU/Linux), running the Elpher client there were no issues. Using the UMn Gopher client, however... 
![umn_dl_bug](https://user-images.githubusercontent.com/561994/68747909-56640580-05b0-11ea-83ef-0ce6be683ce1.png)

Yeah that's just a little monkey being chunky funky, right? Some display issue...

![umn_dl_bug2](https://user-images.githubusercontent.com/561994/68747911-56640580-05b0-11ea-939f-7d8025e24d32.png)

Um.... ***or NOT***
I had a little _lolwut?_ there for a second. Kinda funky, but seems to me it may warrant a bug report or futher investigation at wherever the repo is for the UMn client?

Anyway, can you kill Gophernicus and start say, Geomyidae or Motsognir or something, and since John Goerzen `(Copyright (C) 2000-2005 John Goerzen and the gopher developers` was the latest maintainer, maybe see if you get the same behavior with his pygopherd?

I doubt the behavior will change when you swap out Gophernicus for another gopherd, as it seems to me the UMn client is the only one that I experienced this behavior with,  but if you do wanna swap out Gophernicus for another gopherd I'll be happy to test again :)

**Comment by DavidGriffith** [comment]
I swapped out gophernicus for pygopherd.  No more trash.

![gopher-trash-pygopherd](https://user-images.githubusercontent.com/1289035/68760477-cb423a00-05c6-11ea-86d7-6e70ece9ce76.png)

**Comment by tallship** [comment]
Okay I'm not sure that completely answers our dilemma here. It does address it, but like I inferred (if it wasn't obvious), John probably tested any development of the UMn Gopher client against his own Pygopherd server ;)

So I'm guessing that if there's a deeper issue that might also be revealed in other gopherd's in the same way, it may have gone unnoticed with the combo of UMn Gopher client in conjunction with Pygopherd, considering it was the same dev for both?

The really odd thing I'm coming away with, is that this particular client is the only one that is exhibiting this behavior lol.

@fosslinux , what might be different about the way Gophernicus is serving up these files that is different from Pygopherd, while at the same time not exhibiting such behavior in _some_ other clients?

I'm thinking maybe this should be tested with more clients and another gopherd as well.

@DavidGriffith , if you like, David, I'll fire up a few couple of other clients tonight and test the previous ones too, with the presumption that you're still serving those resources using Pygopherd. Right now, I have to fly a chainsaw for a few hours for the coming ice-age here on the mountain.

**Comment by DavidGriffith** [comment]
It'll still be running pygopherd until I mention the change here.

**Comment by fosslinux** [comment]
Ok, this is very strange. I wonder what UMN Gopher does to make this change happen? I cannot think of anything strange that would make this occur. I will investigate further tonight.

**Comment by tallship** [comment]
Thanks @fosslinux :)

David, I just tried again with the same clients and the same OSes, the only difference this time is the same result as you got in the UMn gopher client - the file d/l'd just fine.

Maybe, if fosslinux doesn't need to test this on Pygopherd, you could switch to say, Motsognir or another gopherd? I think Motsognir will work just as a drop in, and so should Bucktooth, although Geomyidae uses the .gph files instead?

This is actually kinda weird.

**Comment by fosslinux** [comment]
@DavidGriffith, could you please pastbin the _raw source_ of each gophermap leading to the broken file? Ie, the exact gophermap you are using with gophernicus? There seems to be something (not specifing either the port, hostname or using relative paths) that gophernicus's magic to convert into a normal gophermap breaks and makes this happen.

**Comment by fosslinux** [comment]
Well, I think I've found the issue.

There's something very strange going on here.

```
1~fosslinux                            2019-Nov-15 07:41        -       /~fosslinux/    aussies.space   70
```

Is the line gophernicus produces for `gopher://aussies.space`. Note the `2019-Nov-15 07:41        -`. Why is that there?! This is made using the `~` type selector. Am digging....

**Comment by fosslinux** [comment]
@DavidGriffith, would you mind reverting your server to gophernicus so I can confirm the same string is in the middle of the thing?

**Comment by fosslinux** [comment]
This is getting very clear.

The date is there /as further information/ for the end user. However, this means the name is displayed strangely on some gopher clients. So technically, this "bug" is actually two different features from gophernicus and UMN Gopher mainifesting themselves. Most gopher clients (VF1, Lynx, all the others @tallship tested), take the default name from the _selector_ not the _name_. 

So now, the question is that should we remove this string from the name? IMO, this is extra cruft that people mostly don't care about and no-one AFAIK relys on it for anyting. Gophernicus can still use this string internally to sort them in `~`, but I do not think it is nessecary or maybe wanted there.

This still dosen't quite explain why it appears in large sub directories only, however. It's not actually about the layers as per my testing `/a/b/c/d/e/f/g/h/i/j/k` dosen't trigger it, it's a _long_ name that does '/ajdkslahfoiarhtoiarhgrkhngoirnfiasndoignrpignrpaign/` for example. So this could actually also be a string trucation bug in UMN Gopher.

**Comment by DavidGriffith** [comment]
> @DavidGriffith, would you mind reverting your server to gophernicus so I can confirm the same string is in the middle of the name?

Done.

**Comment by DavidGriffith** [comment]
Here's the base gophermap:
````
Feedling sounds can be heard from all around.

0About this gopher	/about.txt
1Interactive Fiction Archive Mirror	/if-archive/
1Yaesu VX-7 Files	/vx7
1Random Amusing Text Files	/text/
1Computer Underground Digest	/cud/

Other places in Gopherspace...

1Floodgap's Veronica-2 Server	/v2/	gopher.floodgap.com	70
1Gogoph, Damien Carol's Gopherspace	/	dams.zapto.org	70
1Quux.Org Mega Server	/	gopher.quux.org	70
1The Gopher Project	/Software/Gopher	gopher.quux.org	70

Stuff...
hLibrary of Congress	URL:http://www.loc.gov
````

This is the base one in the IF Archive:
````
You feel somewhat disoriented as you pass through...

This is the IF-Archive mirror at gopher.661.org.
However, it is not the IF archive itself.
The actual IF Archive is at...

hhttp://www.ifarchive.org	URL:http://www.ifarchive.org
and
hftp://ftp.ifarchive.org	URL:ftp://ftp.ifarchive.org

Unsure how to get started in the world of text adventures?
Try these web sites:
hStarter links at IFWiki	URL:http://www.ifwiki.org/index.php/Starters	
hBrass Lantern Beginner Resources	URL:http://brasslantern.org/beginners/
hThe Interactive Fiction Database	URL:http://ifdb.tads.org/
hThe Interactive Fiction Community Forum	URL:http://intfiction.org/

0README	/if-archive/README
0IF Archive License	/if-archive/misc/license.txt
0Directory Tree	/if-archive/directory-tree
0ls-lR	/if-archive/ls-lR
0Master Index	/if-archive/Master-Index

1Art	/if-archive/art
1Articles	/if-archive/articles
1Books	/if-archive/books
1Download Tools	/if-archive/download-tools
1Emulators	/if-archive/emulators
1Games	/if-archive/games
1Info	/if-archive/info
1Infocom	/if-archive/infocom
1Interpreters Multi	/if-archive/interpreters-multi
1Level9	/if-archive/level9
1Magazines	/if-archive/magazines
1Magnetic Scrolls	/if-archive/magnetic-scrolls
1Mapping Tools	/if-archive/mapping-tools
1Phoenix	/if-archive/phoenix
1Programming	/if-archive/programming
1rec.arts.int-fiction	/if-archive/rec.arts.int-fiction
1rec.games.int-fiction	/if-archive/rec.games.int-fiction
1Scott Adams	/if-archive/scott-adams
1Shells	/if-archive/shells
1Solutions	/if-archive/solutions
1Starters	/if-archive/starters
1Unprocessed	/if-archive/unprocessed
1Utilities	/if-archive/utilities 

Interpreters Quick Links

1Glulx	/if-archive/programming/glulx/interpreters
1Infocom Zcode	/if-archive/infocom/interpreters
1Other	/if-archive/programming
1Tads	/if-archive/programming/tads2/executables
````

This one is for `if-archive/download-tools/amiga`
````
0Index	/if-archive/download-tools/amiga/Index
9DMS	/if-archive/download-tools/amiga/DMS
9LhA_e138.run	/if-archive/download-tools/amiga/LhA_e138.run
9Unzip550x.lha	/if-archive/download-tools/amiga/9Unzip550x.lha
9untgz.lha	/if-archive/download-tools/amiga/9untgz.lha 
````

There is copy of the IF Archive base `gophermap` in `/ifarchive/utilities` which is intended for use by mirror operators.

**Comment by fosslinux** [comment]
Ok, this confirms that the issue is with the date in the name.

I wonder, are you using the `*` selector for if-archive/infocom/interpreters/frotz?

A quick fix would be to add `-nd` to your flags for gophernicus.

**Comment by DavidGriffith** [comment]
There are no other gophermap files in the IF Archive mirror other than the ones I've posted.  So, no `*` selector is being used.

Disabling file sizes and dates using the `-nd` flag does prevent trash from being appended, but is not ideal.  I still think the underlying problem should be fixed.  Have you any suggestions where I should go digging in the UMN Gopher client to get that half of the problem fixed?

**Comment by fosslinux** [comment]
Well, as I said:

> this "bug" is actually two different features from gophernicus and UMN Gopher mainifesting themselves

gophernicus: the date+filesize stuff
UMN Gopher: getting the filename in a strange way.

AFAICT, there's nothing that gophernicus can do about this other than disabling the date+filesize stuff, or display the date + filesize stuff in a different way (idk how that would work though).

To fix UMN Gopher, you would need to go looking at the code that shows what the default filename is. I assume it's the full name.

I'd look at vf1 for inspiration on how this could be handled better in UMN Gopher.

**Comment by DavidGriffith** [comment]
A bit of followup, I think that the function `GDgetEntry()` is faulty.

**Comment by DavidGriffith** [comment]
I'm poking around at how strings are being processed and noticed a strange thing that contradicts what you (@fosslinux) said about directory name lengths.  The bug also happens with `/cud/` and `/text/`.  The files in there aren't long at all.  The reason why the `/vx7/` directory was okay is because that one has/had a `gophermap` file.  Take it away and the wackyness returns. 

I posted about this to gopher-project@other.debian.org to see if I can get some more eyes looking at this and to see why https://github.com/jgoerzen/gopher doesn't have the issues button enabled.

**Comment by tallship** [comment]
John just responded on the gopher list a few hours ago and said he's opened up the issue tracker for the UMN Gopher client.

It seems to me, that there might need to be a discussion on just what may constitute a bug here, since it appears that it can go either way with the server or the client in this case, although it also seems that UMN is the only client that exhibits this behavior and like you said @DavidGriffith , the issue presents for short URIs in shallow directories in the absence of a gophermap.

As far as discussion surrounding what is to be done, I'll leave the rest for the smart people to figure out ;)

**Comment by DavidGriffith** [comment]
I figured out exactly what was going on and fixed it in UM Gopher with https://github.com/jgoerzen/gopher/pull/3.

Would someone please replace the bug label with something to indicate that the problem wasn't with Gophernicus?
