### ISSUE TITLE
"make deb" fails on dpkg 1.19.17

### ISSUE THREAD

**Issue by emilengler** [gophernicus/gophernicus#53]
"make deb" fails on my Debian Buster.
[Here](https://pastebin.com/Xh1Z6RbY) is the log of `make deb`

**Comment by fosslinux** [comment]
@emilengler Can you check if you still have this issue?

**Comment by emilengler** [comment]
```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 5) libwrap0-dev
```

**Comment by fosslinux** [comment]
Yes, that is intended and not a bug, you need to `apt install debhelper libwrap0-dev`.

**Comment by emilengler** [comment]
Thanks, works now. HOWEVER
The build dir is the dir above the repo root.
Example given.

If I run `make deb` in
```
/home/emil/gophernicus
```
I will have the deb file at
```
/home/emil
```

**Comment by fosslinux** [comment]
Yes, this is also by design. dpkg-buildpackage does that, something we have no control over.

>  For a non-native Debian package, e.g., gentoo, you will see the following files in the parent directory (~/gentoo) after building packages: 

https://www.debian.org/doc/manuals/maint-guide/build.en.html
