### ISSUE TITLE
Date overflow bug when running make deb

### ISSUE THREAD

**Issue by cdmnky73** [gophernicus/gophernicus#58]
Platform: Raspberry Pi 3A on Raspbian Buster
Steps to Reproduce: compile via make deb

Crashes when building with this error: 
```
dpkg-deb: building package 'gophernicus' in '../gophernicus_3.1-1_armhf.deb'.
dpkg-deb: error: unable to parse timestamp '253402257599': Numerical result out of range
dh_builddeb: dpkg-deb --build debian/gophernicus .. returned exit code 2
dh_builddeb: Aborting due to earlier error
make[1]: *** [debian/rules:71: binary-arch] Error 2
make[1]: Leaving directory '/home/pi/src/gophernicus'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make: *** [Makefile:57: deb] Error 2
```

[Full Pastebin Output](https://bhh.sh/5ri)

**Comment by fosslinux** [comment]
Hm, I cannot reproduce. Can you check `date` on your local system?

**Comment by cdmnky73** [comment]
```
$ date
Wed Feb  5 10:03:32 EST 2020
$ date +%s
1580915109
```

date looks pretty normal to me

**Comment by fosslinux** [comment]
I'll try on my Pi shortly... maybe it's an ARM thing.

**Comment by cdmnky73** [comment]
i was messing around with this today and the only thing of note that i could figure out is that make deb works in the 3.0.1 branch but not master

**Comment by fosslinux** [comment]
Is this now working?

**Comment by cdmnky73** [comment]
It turns out it was a borked OS install this whole time, it works perfectly on a clean raspberry pi OS install
