### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by fosslinux** [gophernicus/gophernicus#63]
Our current build system is kinda bad. So many hardcoded paths, and it's rather unclean. There's no very easy way for a user to specify their init system and to disable the automatic checking, etc, etc.

I propose that we do **not** use autotools or CMake. Rather, we write our own configure shell script that acts similarly to autotools, and generates a makefile by using sed and the configure options. That way, we can allow users to easily specify options without editing the makefile.

Gophernicus is currently one of the easiest gopher daemons to use and I want to keep it that way. The use of it is often rather easy; I get the most questions about how to set up the build system... they shouldn't need to understand a rather convoluted makefile to install Gophernicus.

**Comment by fosslinux** [comment]
#85

**Comment by ryandesign** [comment]
#85 was merged. Anything left to do here or should this be closed?
