### ISSUE TITLE
is gopher://gophernicus.org being served somewhere?

### ISSUE THREAD

**Issue by estrabd** [gophernicus/gophernicus#79]
If it's up somewhere and I can't find it, please let me know. Otherwise, it's odd that gophernicus doesn't have it's own page in gopherspace.

**Comment by fosslinux** [comment]
`gopher://gopher.gophernicus.org`. This was because the gopher server is on a differnt box to the web server. Really, it should be http.gophernicus.org and gophernicus.org for gopher :P
