### ISSUE TITLE
Access Denied after Install

### ISSUE THREAD

**Issue by porte-g** [gophernicus/gophernicus#83]
Hi !

This post because I'm not able to install gophernicus after many tries...

So, this is what I got :

```
$ sudo gophernicus
Error: Access denied!
____________________________________________________________________________
                                          Gophered by Gophernicus/3.0.1 on `
```

My system is a YUNOHOST based on Debian Stretch :

```
Distributor ID: YunoHost
Description:    YunoHost GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

This is the service file : 

```
 $ cd /lib/systemd/system
 $ sudo nano gophernicus@.service 
 
 [Unit]
 Description=Gophernicus gopher server
  [Service]
 EnvironmentFile=-/etc/default/gophernicus
 EnvironmentFile=-/etc/sysconfig/gophernicus
 ExecStart=/usr/sbin/gophernicus -h %H $OPTIONS
 SuccessExitStatus=1
 StandardInput=socket
 User=nobody

```
And the options file :

```
$ cd /etc/default
$ sudo nano gophernicus

 OPTIONS="-h my.server.fr -l /var/log/gophernicus/server.log -f /usr/lib/gophernicus/filters"
```

I've tried to change permissions according to this issue #15 

```
 $ cd /var
 $ ls -la | grep gopher
 drwxr-xr-x  2 root root  4096 Sep 12 09:57 gopher
 drwxr-xr-x  3  123  1000 4096 Sep 10 18:43 gopher-old
```
```
$ cd /var/gopher
$ ls -la
total 12
drwxr-xr-x  2 root root 4096 Sep 12 09:57 .
drwxr-xr-x 16 root root 4096 Sep 12 09:57 ..
lrwxrwxrwx  1 root root   26 Jul 21  2019 docs -> /usr/share/doc/gophernicus
-rw-r--r--  1 root root 1487 Sep 12 09:57 gophermap

```

During the install process (make deb then dpkg) i got this error : 

```
(Reading database ... 44326 files and directories currently installed.)
Preparing to unpack .../gophernicus_3.0.1-1_armhf.deb ...
Unpacking gophernicus (3.0.1-1) over (3.0.1-1) ...
Setting up gophernicus (3.0.1-1) ...
sed: can't read /etc/default/gophernicus: No such file or directory
sed: can't read /etc/default/gophernicus: No such file or directory
sed: can't read /etc/default/gophernicus: No such file or directory
gophernicus.socket is a disabled or a static unit, not starting it.
```

So I created manually the /etc/default/gophernicus file and relaunch the dpkg command

```
(Reading database ... 44326 files and directories currently installed.)
Preparing to unpack .../gophernicus_3.0.1-1_armhf.deb ...
Unpacking gophernicus (3.0.1-1) over (3.0.1-1) ...
Setting up gophernicus (3.0.1-1) ...
Configuration file '/etc/default/gophernicus'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** gophernicus (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/default/gophernicus ...
gophernicus.socket is a disabled or a static unit, not starting it.
```

Would you have any idea to make it work ? 

Thanks you !

**Comment by augfab** [comment]
Hi,

What revision are you using?

Did you try the more classic approach?
```bash
$ make
$ sudo make install
```
It should add `gophernicus` to `systemd` and enable the service.

I see that the name of the Debian package created by `make deb` is `gophernicus_3.0.1-1_armhf.deb`.
What does this give you?
```bash
$ uname -a
```

**Comment by fosslinux** [comment]
Oops, missed this. What's the output of `systemctl status systemd`.

**Comment by porte-g** [comment]
Hi ! 

I'm using the 3.0.1.

```
$ uname -a
Linux myserver.fr 4.14.84-sunxi #3 SMP Sat Dec 1 07:18:41 CET 2018 armv7l GNU/Linux
```

as sudo
```
$ systemctl status systemd
Unit systemd.service could not be found.
```

I'm going to try the regular make / make install suggested by @augfab

**Comment by porte-g** [comment]
After another try, could it be a host conflict as describe in install section ?

before make and make install, I gave gophernicus.env this param
`
OPTIONS="-h gopher.myserver.fr -D \"gopher\""
`

However, install return give this : 
```
Gopher URL...: gopher://machinemainhost.myserver.fr/
Configuration: /etc/default/gophernicus
```
where host is not correct but conf file in /etc/default is correct

That's what i found in /var/log/gophernicus/server.log

`gopher.myserver.fr:70 - [18/Sep/2020:05:44:23 +0000] "GET 1/ HTTP/1.0" 200 4096 "gopher://machinemainhost.myserver.fr:70/1/" "Unknown gopher client"`

**Comment by fosslinux** [comment]
What gopher client are you trying to use to access gophernicus? Can you post the output of `gophernicus@yourinterfacehere.service` (use tabcomplete to see what yourinterfacehere is)

**Comment by porte-g** [comment]
I was just trying with `$ gophernicus` to see if i could change options
But after trying in firefox with overbyte it seems to display correctly gophermap [https://gopher.floodgap.com/gopher/gw?gopher%3A%2F%2Fhole.gprt.fr](https://gopher.floodgap.com/gopher/gw?gopher%3A%2F%2Fhole.gprt.fr)
I'm not familiar with `gophernicus@yourinterfacehere.service` but tabcomplete give me that : 
```
@::1              @fe00::0          @ff02::1          @ip6-allnodes     @ip6-localhost    @ip6-loopback     @lime2            
@falaf            @ff00::0          @ff02::2          @ip6-allrouters   @ip6-localnet     @ip6-mcastprefix  @localhost  
```

**Comment by fosslinux** [comment]
`gophernicus` is not a standalone binary. It requires a listener in front of it such as systemd or inetd to work correctly. This is where your problem is likely to lie.

**Comment by porte-g** [comment]
Ok thank you I'm gonna look into that !
