### ISSUE TITLE
Recursive directories in /usr/share/doc/gophernicus

### ISSUE THREAD

**Issue by iandstanley** [gophernicus/gophernicus#87]
Just completed the build of the latest version / Gophernicus/3.1 "Dungeon Edition" (built Dec 11 2020)

When testing gopher on localhost I found that in the demo files there is a folder called docs with  a gophernicus folder. Inside that folder is another folder called gophernicus and so on ....

![screen](https://user-images.githubusercontent.com/6939289/101907918-2328e700-3bb3-11eb-932b-80d4c7a089f7.png)

Taking a closer look we see that *make install* does a recursive make 

![screen2](https://user-images.githubusercontent.com/6939289/101908131-8155ca00-3bb3-11eb-8905-24bc013429f7.png)

`
$ ls -la /usr/share/doc/gophernicus/
total 124
drwxr-xr-x    2 root root   4096 Dec 11 12:33 .
drwxr-xr-x 2875 root root 118784 Dec 11 12:28 ..
lrwxrwxrwx    1 root root     26 Dec 11 12:33 gophernicus -> /usr/share/doc/gophernicus
`

I'm guessing that there is a small error in the Makefile with a ln statement 

As far as I can tell from the Makefile 
- make creates the directory */usr/share/doc/gophernicus* 
- make doesn't put anything in it  (make install-docs rather puts the man page into the man folder

I don't know where the error is coming from as I can't see two *ln* statements in the makefile 
- line 147 creates the link   /var/gopher/docs -> /usr/share/doc/gophernicus 

sudo make install somehow performs two ln's but I can't figure out how 

ENV:
building on a raspberry pi / debian

**Comment by fosslinux** [comment]
This problem does not occur in the new build system (#85), which is due to be merged shortly.
