### ISSUE TITLE
Failure to "sudo make deb" on debian/armhf (Raspberry Pi 

### ISSUE THREAD

**Issue by iandstanley** [gophernicus/gophernicus#88]
I was trying to build the .deb package with "sudo make deb" on my Pi 4

the reguar make / sudo make install work fine on my dev pi but I don't have gcc on the home server so decided I would just create a .deb package to copy oer and install. 

Build goes fine upto a point then I see this in the build log before it fails 
-----------
dpkg-deb: building package 'gophernicus' in '../gophernicus_3.1-1_armhf.deb'.
dpkg-deb: error: unable to parse timestamp '253402257599': Numerical result out of range
dh_builddeb: dpkg-deb --build debian/gophernicus .. returned exit code 2
dh_builddeb: Aborting due to earlier error
make[1]: *** [debian/rules:71: binary-arch] Error 2
make[1]: Leaving directory '/home/pi/Projects/gophernicus-3.1'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make: *** [Makefile:56: deb] Error 2

**Comment by iandstanley** [comment]
Building latest master branch (Fri 11 Dec 14:25:21 GMT 2020)

**Comment by fosslinux** [comment]
Hm, this is the second time I have seen this reported on Raspbian. However, I have been unable to reproduce.... unfortunately, we are shortly dropping `make deb` in favor of it being in official repositories (coming mid 2021).

You should just be able to copy the binary over, assuming they are running the same versions of Raspbian.
