### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by hb9kns** [gophernicus/gophernicus#9]
A standard man page is missing.

**Comment by fosslinux** [comment]
I'm happy to take this on.

**Comment by hb9kns** [comment]
Great! And we should also think about noting while the whole thing is gophernicus, the executable is in.gophernicus... which cost me several minutes to figure out when I first noticed it used somewhere (SDF, probably)! ^-^

**Comment by AntonMcClure** [comment]
I can write a man page for Gophernicus unless @fosslinux is still working on it.
