### ISSUE TITLE
Question: ipv6

### ISSUE THREAD

**Issue by gimzmoe** [gophernicus/gophernicus#90]
I've tried opening gophernicus using the ipv6 hostname but that doesn't appear to work.  Is there another way to listen to ipv4 and ipv6?

**Comment by gimzmoe** [comment]
So far I've tried adding -h [ip6addr] to the /etc/config/gophernicus and /etc/sysconfig/gophernicus, and it sort of works.  The server still appears to reference a primary hostname even if it's visited by the secondary hostname.   This second network is a VPN so ideally gopher-visitors would not be redirecting data over the internet but stay within the VPN.

**Comment by zcrayfish** [comment]
The -h flag must be an FQDN, [per the RFC](https://tools.ietf.org/html/rfc1436#:~:text=Fully%20Qualified%20Domain%20Name).
Many clients will choke badly when they run into an IPv6 address in that field.

Can you tell us which platform and super-server daemon (e.g. systemd, xinetd, busybox inetd, etc) you are using?
